spring:
  profiles:
    active: dev,cors  # Default profiles for local development


  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true

  server:
    address: 0.0.0.0
    port: 8080

  web:
    resources:
      static-locations: file:./images/

logging:
  level:
    root: INFO
    sql: DEBUG
    web: TRACE
    com.example: DEBUG
    org.springframework.security: DEBUG