spring:
  data:
    mongodb:
      uri: mongodb://admin:yourStrongPassword@autoshift-mongodb.internal:27017/cars


  web:
    resources:
      static-locations: file:/data/images/


server:
  address: 0.0.0.0
  port: 8080