spring:
  profiles:
    active: dev,cors  # Default profiles for local development


  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: fs.vue.info@gmail.com
    password: icyi tpxs kkty cwxs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    root: INFO
    sql: DEBUG
    web: TRACE
    com.example: DEBUG
    org.springframework.security: DEBUG

