spring:
  data:
    mongodb:
      uri: mongodb://carsUser:carsUserStrongPassword@autoshift-mongodb.internal:27017/cars?authSource=cars
    redis:
      host: autoshift-redis.internal
      port: 6379
      ssl: false


  web:
    resources:
      static-locations: file:/data/images/


server:
  address: 0.0.0.0
  port: 8080
