app = "autoshift-redis"
primary_region = "ams"

[build]
image = "redis:7.2"

# Optional volume if you want persistence
[[mounts]]
source = "redis_data"
destination = "/data"

# No [services] block needed for internal-only services
