# fly.toml app configuration file generated for autoshift-backend on 2025-04-02T23:15:35+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'autoshift-backend'
primary_region = 'ams'

[build]

[env]
  SPRING_DATA_MONGODB_URI = 'mongodb://mongodb-app.internal:27017/cars'
  SPRING_PROFILES_ACTIVE = 'prod,cors'
  SPRING_REDIS_HOST = 'redis-app.internal'
  SPRING_REDIS_PORT = '6379'

[[mounts]]
  source = 'data_volume'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
