app = "autoshift-backend"
primary_region = "ams"

[build]

[env]
SPRING_DATA_MONGODB_URI = "mongodb://autoshift-mongodb.internal:27017/cars"
SPRING_PROFILES_ACTIVE = "prod,cors"
SPRING_REDIS_HOST = "autoshift-redis.internal"
SPRING_REDIS_PORT = "6379"

[[mounts]]
source = "backend_data"
destination = "/data"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
